// <auto-generated />
using System;
using ChillerCoolingSystem_CCS_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChillerCoolingSystem_CCS_.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    partial class HistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChillerCoolingSystem_CCS_.Models.Entities.AlarmEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineKey", "StartUtc");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("ChillerCoolingSystem_CCS_.Models.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcDevice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoneKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/image/CoolingTower.png",
                            Key = "ct3",
                            Location = "Banbury #1,2 , Openmill #1,2,7,8",
                            Name = "CT #3",
                            OpcDevice = "CT-CL.BANBURY.CT3",
                            SortOrder = 1,
                            Type = "Cooling Tower"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/image/CoolingTower.png",
                            Key = "ct7",
                            Location = "Banbury #3 , Openmill #10~12",
                            Name = "CT #7",
                            OpcDevice = "CT-CL.BANBURY.CT7",
                            SortOrder = 2,
                            Type = "Cooling Tower"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/image/Chiller.png",
                            Key = "cl3",
                            Location = "Banbury #2",
                            Name = "Chiller #3",
                            OpcDevice = "CT-CL.BANBURY.CL3",
                            SortOrder = 3,
                            Type = "Chiller",
                            ZoneKey = "ct3"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/image/Chiller.png",
                            Key = "cl5",
                            Location = "Banbury #1",
                            Name = "Chiller #5",
                            OpcDevice = "CT-CL.BANBURY.CL5",
                            SortOrder = 4,
                            Type = "Chiller",
                            ZoneKey = "ct3"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/image/Chiller.png",
                            Key = "cl8",
                            Location = "Banbury #3",
                            Name = "Chiller #8",
                            OpcDevice = "CT-CL.BANBURY.CL8",
                            SortOrder = 5,
                            Type = "Chiller",
                            ZoneKey = "ct7"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/image/Chiller.png",
                            Key = "cl9",
                            Location = "Banbury #3",
                            Name = "Chiller #9",
                            OpcDevice = "CT-CL.BANBURY.CL9",
                            SortOrder = 6,
                            Type = "Chiller",
                            ZoneKey = "ct7"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/image/Chiller.png",
                            Key = "cl10",
                            Location = "Banbury #3",
                            Name = "Chiller #10",
                            OpcDevice = "CT-CL.BANBURY.CL10",
                            SortOrder = 7,
                            Type = "Chiller",
                            ZoneKey = "ct7"
                        });
                });

            modelBuilder.Entity("ChillerCoolingSystem_CCS_.Models.Entities.MachineParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedParameterKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineParameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconKey = "temp-red",
                            Kind = "Temperature",
                            LabelKey = "tempIn",
                            MachineId = 1,
                            ParameterKey = "TempIn",
                            SortOrder = 1,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 2,
                            IconKey = "pressure-teal",
                            Kind = "Pressure",
                            LabelKey = "preWater",
                            MachineId = 1,
                            ParameterKey = "PreWater",
                            SortOrder = 2,
                            Unit = "kg/cm²"
                        },
                        new
                        {
                            Id = 3,
                            IconKey = "temp-blue",
                            Kind = "Temperature",
                            LabelKey = "tempOut",
                            MachineId = 1,
                            ParameterKey = "TempOut",
                            SortOrder = 3,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 4,
                            IconKey = "run-stop",
                            Kind = "Status",
                            LabelKey = "runStop",
                            MachineId = 1,
                            ParameterKey = "RunStop",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IconKey = "temp-gray",
                            Kind = "Temperature",
                            LabelKey = "tempAmbi",
                            MachineId = 1,
                            ParameterKey = "TempAmbi",
                            SortOrder = 5,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 6,
                            IconKey = "fault",
                            Kind = "Fault",
                            LabelKey = "fault",
                            MachineId = 1,
                            ParameterKey = "Fault",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            IconKey = "",
                            Kind = "ErrorFlag",
                            LabelKey = "",
                            LinkedParameterKey = "TempOut",
                            MachineId = 1,
                            ParameterKey = "TempError1",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            IconKey = "",
                            Kind = "ErrorFlag",
                            LabelKey = "",
                            LinkedParameterKey = "PreWater",
                            MachineId = 1,
                            ParameterKey = "TempError2",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            IconKey = "temp-red",
                            Kind = "Temperature",
                            LabelKey = "tempIn",
                            MachineId = 2,
                            ParameterKey = "TempIn",
                            SortOrder = 1,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 10,
                            IconKey = "pressure-teal",
                            Kind = "Pressure",
                            LabelKey = "preWater",
                            MachineId = 2,
                            ParameterKey = "PreWater",
                            SortOrder = 2,
                            Unit = "kg/cm²"
                        },
                        new
                        {
                            Id = 11,
                            IconKey = "temp-blue",
                            Kind = "Temperature",
                            LabelKey = "tempOut",
                            MachineId = 2,
                            ParameterKey = "TempOut",
                            SortOrder = 3,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 12,
                            IconKey = "run-stop",
                            Kind = "Status",
                            LabelKey = "runStop",
                            MachineId = 2,
                            ParameterKey = "RunStop",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 13,
                            IconKey = "temp-gray",
                            Kind = "Temperature",
                            LabelKey = "tempAmbi",
                            MachineId = 2,
                            ParameterKey = "TempAmbi",
                            SortOrder = 5,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 14,
                            IconKey = "fault",
                            Kind = "Fault",
                            LabelKey = "fault",
                            MachineId = 2,
                            ParameterKey = "Fault",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 15,
                            IconKey = "",
                            Kind = "ErrorFlag",
                            LabelKey = "",
                            LinkedParameterKey = "TempOut",
                            MachineId = 2,
                            ParameterKey = "TempError1",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 16,
                            IconKey = "",
                            Kind = "ErrorFlag",
                            LabelKey = "",
                            LinkedParameterKey = "PreWater",
                            MachineId = 2,
                            ParameterKey = "TempError2",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 17,
                            IconKey = "temp-red",
                            Kind = "Temperature",
                            LabelKey = "tempOutWater",
                            MachineId = 3,
                            ParameterKey = "TempOut",
                            SortOrder = 1,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 18,
                            IconKey = "run-stop",
                            Kind = "Status",
                            LabelKey = "runStop",
                            MachineId = 3,
                            ParameterKey = "RunStop",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 19,
                            IconKey = "fault",
                            Kind = "Fault",
                            LabelKey = "fault",
                            MachineId = 3,
                            ParameterKey = "Fault",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 20,
                            IconKey = "temp-red",
                            Kind = "Temperature",
                            LabelKey = "tempOutWater",
                            MachineId = 4,
                            ParameterKey = "TempOut",
                            SortOrder = 1,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 21,
                            IconKey = "run-stop",
                            Kind = "Status",
                            LabelKey = "runStop",
                            MachineId = 4,
                            ParameterKey = "RunStop",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 22,
                            IconKey = "fault",
                            Kind = "Fault",
                            LabelKey = "fault",
                            MachineId = 4,
                            ParameterKey = "Fault",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 23,
                            IconKey = "run-stop",
                            Kind = "Status",
                            LabelKey = "runStop",
                            MachineId = 5,
                            ParameterKey = "RunStop",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 24,
                            IconKey = "fault",
                            Kind = "Fault",
                            LabelKey = "fault",
                            MachineId = 5,
                            ParameterKey = "Fault",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 25,
                            IconKey = "run-stop",
                            Kind = "Status",
                            LabelKey = "runStop",
                            MachineId = 6,
                            ParameterKey = "RunStop",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 26,
                            IconKey = "fault",
                            Kind = "Fault",
                            LabelKey = "fault",
                            MachineId = 6,
                            ParameterKey = "Fault",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 27,
                            IconKey = "temp-red",
                            Kind = "Temperature",
                            LabelKey = "tempOutWater",
                            MachineId = 7,
                            ParameterKey = "TempOut",
                            SortOrder = 1,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 28,
                            IconKey = "run-stop",
                            Kind = "Status",
                            LabelKey = "runStop",
                            MachineId = 7,
                            ParameterKey = "RunStop",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 29,
                            IconKey = "fault",
                            Kind = "Fault",
                            LabelKey = "fault",
                            MachineId = 7,
                            ParameterKey = "Fault",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("ChillerCoolingSystem_CCS_.Models.Entities.TagHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Good")
                        .HasColumnType("bit");

                    b.Property<string>("MachineKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineKey", "TimestampUtc");

                    b.ToTable("TagHistoryEntries");
                });

            modelBuilder.Entity("ChillerCoolingSystem_CCS_.Models.Entities.MachineParameter", b =>
                {
                    b.HasOne("ChillerCoolingSystem_CCS_.Models.Entities.Machine", "Machine")
                        .WithMany("Parameters")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ChillerCoolingSystem_CCS_.Models.Entities.Machine", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
